name: Run checks on Kedro-Docker

on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - "kedro-airflow/**"
      - "kedro-datasets/**"
      - "kedro-telemetry/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "kedro-airflow/**"
      - "kedro-datasets/**"
      - "kedro-telemetry/**"
  schedule:
    # Run every day at midnight (UTC time)
    - cron: '0 0 * * *'

jobs:
  unit-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    uses: ./.github/workflows/reusable/unit-tests.yml
    with:
      plugin: kedro-docker
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  lint:
    uses: ./.github/workflows/reusable/lint.yml
    with:
      plugin: kedro-docker
      os: ubuntu-latest
      python-version: "3.8"

  e2e-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    uses: ./.github/workflows/reusable/e2e-tests.yml
    with:
      plugin: kedro-docker
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}